name: Build

on:
  push:
    branches: 
      - main
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'NOTICE'
      - 'README*'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'NOTICE'
      - 'README*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout

      - uses: actions/setup-java@v1
        name: set up jdk 11
        with:
          java-version: 11

      - name: build with maven
        run: mvn verify -Pnative

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout

      - uses: actions/setup-java@v1
        name: set up jdk 11
        with:
          java-version: 11

      - name: build with maven
        # Skip integration tests. TestContainers does not support Windows Server 2019: https://github.com/testcontainers/testcontainers-java/issues/2960
        run: mvn test
